#!/bin/bash
#set -x

find $PWD -type l | while read file; do
    sdir=${file%/*}
    target=$(readlink $file)
    tbase=${target##*/}
    tdir=${target%/*}
    fix=''
    
    [[ ! -a $target ]] && {
	echo -n "broken: $base->$target"
	if [[ -a $sdir/../$tbase ]]; then 
	    fix=$(realpath $sdir/../$tbase)
	    echo -n " fix: ln -sf $fix $file"
	    ln -sf $fix $file
	fi
	echo
    }
done
		       
