// This file was predominately generated by Claude Sonnet 4.6
#define _GNU_SOURCE
#include <sys/syscall.h>
#include <sys/stat.h>
#include "incs.h"
#include "modinfo.h"
#include "module_patch.h"

// init_module and delete_module are Linux syscalls.
// glibc does not expose them in public headers so we call them via syscall(2).

static int
kld_init_module(void *image, unsigned long len, const char *params)
{
  return (int)syscall(SYS_init_module, image, len, params);
}

static int
kld_delete_module(const char *name, unsigned int flags)
{
  return (int)syscall(SYS_delete_module, name, flags);
}

// Attempt init_module and handle EEXIST according to kldopts.
// Factored out so the same logic covers both the first attempt and the
// post-delete retry in RELOAD.
static int
do_init_module(void *image, size_t image_size, bo_t *bo)
{
  const char *kofnm = bo->kofnm;
  const char *modnm = bo->modnm;
  kldopts_t   opts  = bo->kldopts;

  int rc = kld_init_module(image, (unsigned long)image_size, "");
  if (rc == 0) {
    VPRINT("%s: loaded as %s\n", kofnm, modnm);
    bo->loaded = 1;
    return 0;
  }

  int saved_errno = errno;
  if (saved_errno != EEXIST) {
    EPRINT(stderr, "%s: init_module: %s\n", kofnm, strerror(saved_errno));
    return -1;
  }

  // Module already present in the kernel (EEXIST).

  if (opts & KLDOPT_SHARED) {
    VPRINT("%s: already loaded, skipping (SHARED)\n", modnm);
    bo->loaded = 1;
    return 0;
  }

  if (opts & KLDOPT_RELOAD) {
    VPRINT("%s: already loaded, unloading for reload (RELOAD)\n", modnm);
    // O_NONBLOCK: return EWOULDBLOCK immediately if the module is in use
    // rather than blocking indefinitely.
    if (kld_delete_module(modnm, O_NONBLOCK) != 0) {
      EPRINT(stderr, "%s: delete_module: %s\n", modnm, strerror(errno));
      return -1;
    }
    rc = kld_init_module(image, (unsigned long)image_size, "");
    if (rc == 0) {
      VPRINT("%s: reloaded as %s\n", kofnm, modnm);
      bo->loaded = 1;
      return 0;
    }
    EPRINT(stderr, "%s: init_module (after reload): %s\n",
           kofnm, strerror(errno));
    return -1;
  }

  // Neither SHARED nor RELOAD: already-loaded is an error.
  EPRINT(stderr, "%s: already loaded\n", modnm);
  return -1;
}

// Load the kernel object represented by bo into the kernel, registering
// it under bo->modnm.
//
// Maps the .ko file privately (MAP_PRIVATE, copy-on-write), patches the
// module name field in memory if bo->modnm differs from the compiled-in
// name, then calls init_module.  The .ko file on disk is never modified.
//
// kldopts semantics:
//   KLDOPT_SHARED  - if the module is already loaded treat it as success.
//   KLDOPT_RELOAD  - if already loaded, unload then retry.
//   KLDOPT_PERPROC - ignored for now.
//
// Returns 0 on success, -1 on failure.
int
loadBO(bo_t *bo)
{
  int    rc;
  void  *map  = MAP_FAILED;
  size_t sz   = 0;

  VPRINT("loading %s as %s opts:%#lx\n", bo->kofnm, bo->modnm, bo->kldopts);

  // Get the exact file size for init_module (mmap rounds up to page boundary
  // but init_module must receive the true byte count).
  struct stat st;
  if (fstat(bo->kofd, &st) < 0) {
    EPRINT(stderr, "%s: fstat: %s\n", bo->kofnm, strerror(errno));
    return -1;
  }
  sz = (size_t)st.st_size;

  // MAP_PRIVATE gives a copy-on-write mapping: modifications stay in our
  // private pages and never touch the .ko file on disk.
  map = mmap(NULL, sz, PROT_READ | PROT_WRITE, MAP_PRIVATE, bo->kofd, 0);
  if (map == MAP_FAILED) {
    EPRINT(stderr, "%s: mmap: %s\n", bo->kofnm, strerror(errno));
    return -1;
  }

  if (bo->forcemodnm) {
    // Name is overridden; patch the compiled-in name in the ELF image.
    // bo->komodnm is populated by addbo when it read modinfo; the only
    // case where it is NULL is when both modnm and kldopts were forced on
    // the CLI so addbo skipped reading modinfo entirely.
    const char  *orig = bo->komodnm;
    kld_modinfo  mi   = {0};
    if (!orig) {
      if (kld_read_modinfo(bo->kofnm, bo->kofd, &mi) == 0 && mi.name)
        orig = mi.name;
      else
        EPRINT(stderr, "%s: WARNING: cannot determine compiled-in name, "
               "skipping name patch\n", bo->kofnm);
    }
    if (orig) {
      VPRINT("%s: patching module name '%s' -> '%s'\n",
             bo->kofnm, orig, bo->modnm);
      if (kld_patch_module_name_image(map, sz, orig, bo->modnm) < 0) {
        EPRINT(stderr, "%s: could not patch module name\n", bo->kofnm);
        kld_free_modinfo(&mi);
        munmap(map, sz);
        return -1;
      }
    }
    kld_free_modinfo(&mi);
  }

  rc = do_init_module(map, sz, bo);
  munmap(map, sz);
  return rc;
}
