// This file was predominately generated by Claude Sonnet 4.6
#define _GNU_SOURCE
#include <sys/syscall.h>
#include <sys/stat.h>
#include "incs.h"
#include "modinfo.h"

// MODULE_NAME_LEN is defined in <linux/module.h> (kernel header, not
// available in userspace).  The value has been 56 since at least Linux 2.6
// and is stable across all kernel versions kld targets.
#ifndef MODULE_NAME_LEN
#define MODULE_NAME_LEN 56
#endif

// init_module and delete_module are Linux syscalls.
// glibc does not expose them in public headers so we call them via syscall(2).

static int
kld_init_module(void *image, unsigned long len, const char *params)
{
  return (int)syscall(SYS_init_module, image, len, params);
}

static int
kld_delete_module(const char *name, unsigned int flags)
{
  return (int)syscall(SYS_delete_module, name, flags);
}

// Patch the module name stored in .gnu.linkonce.this_module.
//
// The kernel uses struct module.name (a char[MODULE_NAME_LEN] field near
// the start of that section) as the definitive module name for lsmod and
// rmmod.  Rather than hard-coding the struct field offset (which varies
// between kernel versions), we scan the section bytes for orig_name and
// replace it in-place, zeroing the remainder of the fixed-size field.
//
// image must be a writable mapping (MAP_PRIVATE).
// Returns 0 if the name was found and patched, -1 otherwise.
static int
patch_module_name(void *image, size_t image_size,
                  const char *orig_name, const char *new_name)
{
  size_t orig_len = strlen(orig_name);
  size_t new_len  = strlen(new_name);

  if (new_len >= MODULE_NAME_LEN) {
    EPRINT(stderr, "module name '%s' too long (max %d chars)\n",
           new_name, MODULE_NAME_LEN - 1);
    return -1;
  }

  elf_version(EV_CURRENT);
  Elf *elf = elf_memory((char *)image, image_size);
  if (!elf) {
    EPRINT(stderr, "elf_memory: %s\n", elf_errmsg(-1));
    return -1;
  }

  size_t shstrndx;
  if (elf_getshdrstrndx(elf, &shstrndx) != 0) {
    elf_end(elf);
    return -1;
  }

  int      rc  = -1;
  Elf_Scn *scn = NULL;
  while ((scn = elf_nextscn(elf, scn)) != NULL) {
    GElf_Shdr shdr;
    if (gelf_getshdr(scn, &shdr) == NULL) continue;
    const char *sname = elf_strptr(elf, shstrndx, shdr.sh_name);
    if (!sname || strcmp(sname, ".gnu.linkonce.this_module") != 0) continue;

    if (shdr.sh_offset + shdr.sh_size > (Elf64_Off)image_size) break;

    // Patch directly in the raw image bytes at the section's file offset
    // to avoid any libelf buffering or byte-order translation concerns.
    char  *sec = (char *)image + shdr.sh_offset;
    size_t ssz = (size_t)shdr.sh_size;

    for (size_t i = 0; i + orig_len < ssz; i++) {
      if (memcmp(&sec[i], orig_name, orig_len + 1) == 0) {
        size_t field_sz = MODULE_NAME_LEN;
        if (i + field_sz > ssz) field_sz = ssz - i;
        memset(&sec[i], 0, field_sz);      // zero the whole name field
        memcpy(&sec[i], new_name, new_len);
        rc = 0;
        break;
      }
    }
    break; // section found; stop regardless
  }

  elf_end(elf);
  if (rc < 0)
    EPRINT(stderr, "name '%s' not found in .gnu.linkonce.this_module\n",
           orig_name);
  return rc;
}

// Attempt init_module and handle EEXIST according to kldopts.
// Factored out so the same logic covers both the first attempt and the
// post-delete retry in RELOAD.
static int
do_init_module(void *image, size_t image_size, bo_t *bo)
{
  const char *kofnm = bo->kofnm;
  const char *modnm = bo->modnm;
  kldopts_t   opts  = bo->kldopts;

  int rc = kld_init_module(image, (unsigned long)image_size, "");
  if (rc == 0) {
    VPRINT("%s: loaded as %s\n", kofnm, modnm);
    bo->loaded = 1;
    return 0;
  }

  int saved_errno = errno;
  if (saved_errno != EEXIST) {
    EPRINT(stderr, "%s: init_module: %s\n", kofnm, strerror(saved_errno));
    return -1;
  }

  // Module already present in the kernel (EEXIST).

  if (opts & KLDOPT_SHARED) {
    VPRINT("%s: already loaded, skipping (SHARED)\n", modnm);
    bo->loaded = 1;
    return 0;
  }

  if (opts & KLDOPT_RELOAD) {
    VPRINT("%s: already loaded, unloading for reload (RELOAD)\n", modnm);
    // O_NONBLOCK: return EWOULDBLOCK immediately if the module is in use
    // rather than blocking indefinitely.
    if (kld_delete_module(modnm, O_NONBLOCK) != 0) {
      EPRINT(stderr, "%s: delete_module: %s\n", modnm, strerror(errno));
      return -1;
    }
    rc = kld_init_module(image, (unsigned long)image_size, "");
    if (rc == 0) {
      VPRINT("%s: reloaded as %s\n", kofnm, modnm);
      bo->loaded = 1;
      return 0;
    }
    EPRINT(stderr, "%s: init_module (after reload): %s\n",
           kofnm, strerror(errno));
    return -1;
  }

  // Neither SHARED nor RELOAD: already-loaded is an error.
  EPRINT(stderr, "%s: already loaded\n", modnm);
  return -1;
}

// Load the kernel object represented by bo into the kernel, registering
// it under bo->modnm.
//
// Maps the .ko file privately (MAP_PRIVATE, copy-on-write), patches the
// module name field in memory if bo->modnm differs from the compiled-in
// name, then calls init_module.  The .ko file on disk is never modified.
//
// kldopts semantics:
//   KLDOPT_SHARED  - if the module is already loaded treat it as success.
//   KLDOPT_RELOAD  - if already loaded, unload then retry.
//   KLDOPT_PERPROC - ignored for now.
//
// Returns 0 on success, -1 on failure.
int
loadBO(bo_t *bo)
{
  int    rc;
  void  *map  = MAP_FAILED;
  size_t sz   = 0;

  VPRINT("loading %s as %s opts:%#lx\n", bo->kofnm, bo->modnm, bo->kldopts);

  // Get the exact file size for init_module (mmap rounds up to page boundary
  // but init_module must receive the true byte count).
  struct stat st;
  if (fstat(bo->kofd, &st) < 0) {
    EPRINT(stderr, "%s: fstat: %s\n", bo->kofnm, strerror(errno));
    return -1;
  }
  sz = (size_t)st.st_size;

  // MAP_PRIVATE gives a copy-on-write mapping: modifications stay in our
  // private pages and never touch the .ko file on disk.
  map = mmap(NULL, sz, PROT_READ | PROT_WRITE, MAP_PRIVATE, bo->kofd, 0);
  if (map == MAP_FAILED) {
    EPRINT(stderr, "%s: mmap: %s\n", bo->kofnm, strerror(errno));
    return -1;
  }

  if (bo->forcemodnm) {
    // Name is overridden; patch the compiled-in name in the ELF image.
    // bo->komodnm is populated by addbo when it read modinfo; the only
    // case where it is NULL is when both modnm and kldopts were forced on
    // the CLI so addbo skipped reading modinfo entirely.
    const char  *orig = bo->komodnm;
    kld_modinfo  mi   = {0};
    if (!orig) {
      if (kld_read_modinfo(bo->kofnm, bo->kofd, &mi) == 0 && mi.name)
        orig = mi.name;
      else
        EPRINT(stderr, "%s: WARNING: cannot determine compiled-in name, "
               "skipping name patch\n", bo->kofnm);
    }
    if (orig) {
      VPRINT("%s: patching module name '%s' -> '%s'\n",
             bo->kofnm, orig, bo->modnm);
      if (patch_module_name(map, sz, orig, bo->modnm) < 0) {
        EPRINT(stderr, "%s: could not patch module name\n", bo->kofnm);
        kld_free_modinfo(&mi);
        munmap(map, sz);
        return -1;
      }
    }
    kld_free_modinfo(&mi);
  }

  rc = do_init_module(map, sz, bo);
  munmap(map, sz);
  return rc;
}
