#ifndef APP_H_EXT_
#define APP_H_EXT_

#ifdef __cplusplus
extern "C" {
#endif

#define NO_APP_GOT_ENTRIES
typedef struct {
// GOT Declarations
void* dummy; // No GOT entries found, dummy entry to avoid empty struct
} app_got_t;

extern app_got_t* app_got; // this is defined in init.c generated by kcc

#define DEFINE_GOT_FUNC(func_name, rettype, args) \
static inline rettype func_name args { \
asm volatile ( \
   "jmp *%0" \
   : \
   : "r"(app_got->func_name) \
   ); \
   unreachable(); \
}

#ifdef __cplusplus
}
#endif

#endif // APP_H_EXT_